# Introduction to pandas Data Structures

## Series

**A Series is a one-dimensional array-like object containing a sequence of values and an associated array of data labels, called its index.**

In [2]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([1,-2,0,-5])
#obj = pd.Series([1,-2,0,-5],index = ['a','b','c','d']) #with indexing

In [4]:
obj.values,obj.index

(array([ 1, -2,  0, -5], dtype=int64), RangeIndex(start=0, stop=4, step=1))

In [5]:
obj

0    1
1   -2
2    0
3   -5
dtype: int64

In [6]:
obj[0]

1

In [7]:
obj.index = ['a','b','c','d']

In [8]:
obj.values

array([ 1, -2,  0, -5], dtype=int64)

In [9]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
obj

a    1
b   -2
c    0
d   -5
dtype: int64

In [11]:
obj['a'],obj.a

(1, 1)

In [12]:
obj['a':'c']

a    1
b   -2
c    0
dtype: int64

Using NumPy functions or NumPy-like operations, such as filtering with a boolean
array, scalar multiplication, or applying math functions, will preserve the index-value

In [13]:
obj.values

array([ 1, -2,  0, -5], dtype=int64)

In [14]:
obj2 = pd.Series([1,2,-2,0],index=['c','a','b','d'])

In [15]:
obj[ obj2 > 0 ]

a    1
c    0
dtype: int64

same length and index should contain on the both array. if indexes are scattered there is no problem.

In [16]:
obj2 * 2

c    2
a    4
b   -4
d    0
dtype: int64

In [17]:
'd' in obj2

True

In [18]:
np.exp(obj2)

c    2.718282
a    7.389056
b    0.135335
d    1.000000
dtype: float64