# ndarray

## Creating ndarrays

In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
array1 = np.array(data1)
array1
#array1 = np.array([1,2,3,4]) #another
#array1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
#2D array
data2 = [[1,2,3],[4,5,6]]
ara2 = np.array(data2)
ara2[0][1]

2

In [4]:
ara2.ndim

2

In [5]:
ara2.shape,ara2.dtype

((2, 3), dtype('int32'))

In [6]:
array1.shape,array1.dtype

((5,), dtype('float64'))

### np.zeros()

- np.zeros() will create arrays with the vlaue zeros.

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
ara1 = np.zeros( (3,6) )
ara1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
ara1 = np.zeros( (2,2,3) )
ara1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
ara1[0][0][1]

0.0

### np.ones()

In [11]:
np.ones((2,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

 It’s not safe to assume that np.empty will return an array of all zeros. In some cases, it may return uninitialized **“garbage”** values.

In [12]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
ara = np.empty((3,3)) #used to create fixed size array
for i in range(0,3):
    for j in range(0,3):
        ara[i][j] = j
ara

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

###  np.arange()

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Data types for ndarrays

In [16]:
np.array([1,2,3],dtype=np.float64)

array([1., 2., 3.])

In [17]:
np.array([1,2,3],dtype=np.int32)

array([1, 2, 3])

### astype() - change datatype of full array

In [18]:
ara = np.array([1,2,3,4])
ara.dtype

dtype('int32')

In [19]:
float_arr = ara.astype(np.float64) #returns float ara,does not change main array.
float_arr.dtype

dtype('float64')

In [20]:
numeric_string = np.array( ['-9.2','1.2','1.5034'],dtype=np.string_ )
numeric_string

array([b'-9.2', b'1.2', b'1.5034'], dtype='|S6')

In [21]:
float_arr = numeric_string.astype(float)
float_arr

array([-9.2   ,  1.2   ,  1.5034])

### Arithmetic with NumPy Arrays

Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this **vectorization**.

In [22]:
ara = np.array([ [2,9,16],[25,36,49] ],dtype=np.int32)

In [23]:
ara2 = np.array([ [22,19,161],[5,3,49] ],dtype=np.int32)

In [24]:
ara * ara #multiply positional element of both ara

array([[   4,   81,  256],
       [ 625, 1296, 2401]])

In [25]:
ara+ara

array([[ 4, 18, 32],
       [50, 72, 98]])

In [26]:
0 / ara

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# each element rises by power 2
ara ** 2

array([[   4,   81,  256],
       [ 625, 1296, 2401]], dtype=int32)

In [28]:
#compares positional element of both ara
ara > ara2 

array([[False, False, False],
       [ True,  True, False]])

### Basic Indexing and Slicing

In [29]:
ara = np.arange(10)
ara

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
ara[1]

1

In [31]:
ara[-1:-6:-1]

array([9, 8, 7, 6, 5])

In [32]:
ara[0:8],ara[:8],ara[:10:2],ara[:]

(array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([0, 2, 4, 6, 8]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [33]:
ara[4:7] = 0
ara

array([0, 1, 2, 3, 0, 0, 0, 7, 8, 9])

- arr_slice, the mutations are reflected in the **original ara**

In [34]:
#this is not a copy, this is just a view
sliced_ara = ara[4:7]
sliced_ara

array([0, 0, 0])

In [35]:
#Changing the element in the sliced_ara will also change the value in the original ara
sliced_ara[:] = 111
ara #4th,5th and 6th indexes has changed into 111

array([  0,   1,   2,   3, 111, 111, 111,   7,   8,   9])

In [36]:
#creating copy of a slice
slice_ = ara[4:7].copy()
slice_

array([111, 111, 111])

In [37]:
slice_[:] = 2
ara[:] #no effect on origianl ara

array([  0,   1,   2,   3, 111, 111, 111,   7,   8,   9])

In [38]:
slice_[:]

array([2, 2, 2])

In [39]:
ara = np.array( [ [1,2,3],[4,5,6],[7,8,9] ] )
ara

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
ara[0][1]

2

In [41]:
ara[0,2]

3

### 2D,3D Slicing

<img src = images/slicing.PNG >

In [42]:
ara[0:3,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [43]:
arr3d = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])

In [44]:
arr3d[1][0][1]

8

In [45]:
arr3d[:,:,2:3] #each colon acts as a loop. so there is total 3 loop.

array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])

### Boolean Indexing

Suppose each name corresponds to a row in the 'data' array and we wanted to select data all the rows with corresponding name 'Bob'.

In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [47]:
data = np.random.randn(7, 4)
data

array([[ 0.42393625,  0.52587512,  0.78528734, -0.84468696],
       [-0.94898509, -0.28504632, -0.40579876, -0.10758262],
       [ 0.99532072, -1.69937   , -0.18617563, -0.73474013],
       [-0.46305101, -1.34030124, -1.19059754,  1.18187547],
       [ 2.17426536, -0.81802507, -0.80290232,  0.62801144],
       [-0.95688177,  0.84949245,  0.3057313 , -0.40967697],
       [ 0.0967572 ,  0.52863619,  1.13527746,  1.27073889]])

In [48]:
#returns a boolean array. Any index is true if the index contains string 'Bob' , otherwise it is false.
names == 'Bob' 

array([ True, False, False,  True, False, False, False])

In [49]:
# names == 'Bob' gives the array index where it is true.
data[ names == 'Bob' ]

array([[ 0.42393625,  0.52587512,  0.78528734, -0.84468696],
       [-0.46305101, -1.34030124, -1.19059754,  1.18187547]])

In [50]:
data[  names == 'Bob',2: ]

array([[ 0.78528734, -0.84468696],
       [-1.19059754,  1.18187547]])

In [51]:
data[  names == 'Bob', 3 ]

array([-0.84468696,  1.18187547])

- To select everything but 'Bob', we can either **use != or negate the condition using ~**

In [52]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [53]:
data[ names != 'Bob' ]

array([[-0.94898509, -0.28504632, -0.40579876, -0.10758262],
       [ 0.99532072, -1.69937   , -0.18617563, -0.73474013],
       [ 2.17426536, -0.81802507, -0.80290232,  0.62801144],
       [-0.95688177,  0.84949245,  0.3057313 , -0.40967697],
       [ 0.0967572 ,  0.52863619,  1.13527746,  1.27073889]])

In [54]:
data[ ~(names == 'Bob') ]

array([[-0.94898509, -0.28504632, -0.40579876, -0.10758262],
       [ 0.99532072, -1.69937   , -0.18617563, -0.73474013],
       [ 2.17426536, -0.81802507, -0.80290232,  0.62801144],
       [-0.95688177,  0.84949245,  0.3057313 , -0.40967697],
       [ 0.0967572 ,  0.52863619,  1.13527746,  1.27073889]])

In [55]:
cond = names == 'Bob'
data[ ~cond ]

array([[-0.94898509, -0.28504632, -0.40579876, -0.10758262],
       [ 0.99532072, -1.69937   , -0.18617563, -0.73474013],
       [ 2.17426536, -0.81802507, -0.80290232,  0.62801144],
       [-0.95688177,  0.84949245,  0.3057313 , -0.40967697],
       [ 0.0967572 ,  0.52863619,  1.13527746,  1.27073889]])

- The Python keywords 'and' and 'or' do not work with boolean arrays. use **&** and **|** instead.

In [56]:
mask = (names=='Bob') | (names=='Will')
mask

array([ True, False,  True,  True,  True, False, False])

- Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.

In [57]:
data[mask]

array([[ 0.42393625,  0.52587512,  0.78528734, -0.84468696],
       [ 0.99532072, -1.69937   , -0.18617563, -0.73474013],
       [-0.46305101, -1.34030124, -1.19059754,  1.18187547],
       [ 2.17426536, -0.81802507, -0.80290232,  0.62801144]])

### Setting values with boolean arrays

In [58]:
data[ data<0] = 0
data

array([[0.42393625, 0.52587512, 0.78528734, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.99532072, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.18187547],
       [2.17426536, 0.        , 0.        , 0.62801144],
       [0.        , 0.84949245, 0.3057313 , 0.        ],
       [0.0967572 , 0.52863619, 1.13527746, 1.27073889]])

- setting whole row or column

In [59]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.84949245, 0.3057313 , 0.        ],
       [0.0967572 , 0.52863619, 1.13527746, 1.27073889]])

In [60]:
ara = np.empty((8,4))
ara

array([[ 7.12263285e+149,  1.12856170e+277, -3.38460684e+125,
         3.53882138e-308],
       [ 1.57434270e+161,  1.87255730e-311,  1.79043021e-280,
         1.12525927e+169],
       [ 2.77084720e-181,  6.21806156e+175,  5.18761342e-313,
         1.59700248e+241],
       [ 1.49091424e-310,  1.00562508e-248,  2.64089007e-313,
         1.02605457e-307],
       [ 6.66310044e-191,  4.03162364e-270,  1.83160638e-260,
         7.86668957e-251],
       [ 4.99183066e+223,  4.45196962e+252,  7.33720825e+223,
         1.29732998e-311],
       [ 1.08646184e-311,  3.63964718e-310,  1.78005909e-306,
         8.41435797e-220],
       [ 2.10053203e-301,  1.36178756e+281,  8.69972242e+183,
         1.81596891e-152]])

In [61]:
for i in range(8):
    ara[i] = i
ara

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [62]:
col = [1,2]
ara[:,col ]

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.],
       [7., 7.]])

In [63]:
row = [0,3]
ara[row]

array([[0., 0., 0., 0.],
       [3., 3., 3., 3.]])

In [64]:
rev_row = [-1,-3,-8]
ara[rev_row]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.]])

In [65]:
rev_col = [-1,-3]
ara[:,rev_col]

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.],
       [7., 7.]])

### fancy indexing and np.arange().reshape()

In [66]:
ara = np.arange(32).reshape((8,4))
ara

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [67]:
ara[  [0,2,4,5] ,[0,2,1,3]  ]

array([ 0, 10, 17, 23])

In [68]:
ara [  [0,2,4,5] ][ :,[0,2,1,3] ]

array([[ 0,  2,  1,  3],
       [ 8, 10,  9, 11],
       [16, 18, 17, 19],
       [20, 22, 21, 23]])

### Transposing,dot product,swapping address

In [69]:
ara = np.arange(15).reshape((3,5))
ara

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
#transpose
araT = ara.T
araT

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [71]:
#dot product
np.dot(ara,araT)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

### Transpose for higher dimensional

In [72]:
ara3d = np.arange(24).reshape(2,3,4)
ara3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [73]:
ara3d.shape

(2, 3, 4)

by **defalut transpose is (0,1,2)** where '0' indicates the first index of 'ara3d.shape' and 1 and 2 respectively indicates the second and third index of the 'ara3d.shape'. in transpose() **0 -> x_axes, 1 -> y_axes and 2 -> z_axes.** if we declare **transpose(1,0,2) that means the array shape will be rearranged from (2,3,4) to (3,2,4).** the rearrange process is given below.
<img src = images/rearrange.PNG >

In [74]:
ara3d.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [75]:
ara3d.transpose(2,1,0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [76]:
ara = np.arange(4).reshape((2,2))
ara

array([[0, 1],
       [2, 3]])

- ara.T and ara.transpose() both **returns a view**

In [77]:
arat = ara.T
arat

array([[0, 2],
       [1, 3]])

- **array.swapaxes**

In [78]:
S_ara = np.arange(12).reshape((2,2,3))
S_ara

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [79]:
S_ara.shape

(2, 2, 3)

This similar to the higher dimensional transpose except the rearranging order. Here **rearrange occurs column wise.**
<img src = images/swap.PNG >


In [80]:
S_ara.swapaxes(2,1)

array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])

### Universal Functions: Fast Element-Wise Array Functions

#### np.sqrt

In [81]:
ara = np.arange(1,13)
ara

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
np.sqrt(ara)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162])

#### np.random.randn

In [83]:
rand = np.random.randn(1,8)
rand

array([[ 0.13056164,  0.33094886, -1.32722783, -1.14138378,  1.32200347,
        -0.20452021,  0.75952519,  0.72727826]])

In [84]:
rand = np.random.randn(8)
rand

array([ 0.5125952 ,  1.83334523,  0.45925266,  0.74845282,  1.29019743,
       -0.43464066, -0.41981319, -0.08280584])

#### np.maximum

In [85]:
np.maximum(10,50)

50

#### np.modf (separates and return floating points and decimals individually)

In [86]:
floatPart, decimalPart = np.modf(rand)

In [87]:
floatPart

array([ 0.5125952 ,  0.83334523,  0.45925266,  0.74845282,  0.29019743,
       -0.43464066, -0.41981319, -0.08280584])

In [88]:
decimalPart

array([ 0.,  1.,  0.,  0.,  1., -0., -0., -0.])

#### np.abs (absolute value)

In [89]:
np.abs(decimalPart)

array([0., 1., 0., 0., 1., 0., 0., 0.])

In [90]:
np.exp,log,log10,log2

NameError: name 'log' is not defined

In [ ]:
ara = np.arange(1,10)
ara = ara.astype(int)
ara

In [ ]:
np.exp(ara)

In [ ]:
np.log(ara)

In [ ]:
np.log10(ara)

In [ ]:
np.log2(ara)

#### sin,sinh,cos,cosh,tan,tanh

In [ ]:
np.sin(ara),np.sinh(ara),np.cos(ara),np.cosh(ara),np.tan(ara),np.tanh(ara)

### Expressing Conditional Logic as Array Operations

#### np.where

In [93]:
rand = np.random.randn(4,4)
rand

array([[ 0.63479909,  0.13015463, -0.47205087, -0.31427073],
       [-0.37141056, -1.01804921, -0.71129955,  1.33318379],
       [-0.05058098, -1.44687008, -0.34387203, -0.0046226 ],
       [ 0.42729105,  0.46741808,  1.14422914,  0.84377899]])

In [94]:
rand > 0

array([[ True,  True, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

np.where works like: if rand>0 then replace with 2 else replace with -2

In [95]:
np.where(rand > 0,2,-2)

array([[ 2,  2, -2, -2],
       [-2, -2, -2,  2],
       [-2, -2, -2, -2],
       [ 2,  2,  2,  2]])

The code given below is works like: if rand>0 then replace with 2 else replace with the same positional value of 'rand' array. argument 'rand' should be equal size with the array that was used in the condition.

In [101]:
np.where(rand > 0, 2, rand)

array([[ 2.        ,  2.        , -0.47205087, -0.31427073],
       [-0.37141056, -1.01804921, -0.71129955,  2.        ],
       [-0.05058098, -1.44687008, -0.34387203, -0.0046226 ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

### Mathematical and Statistical Methods

#### np.mean,np.std,np.sum,arr.mean(axis=1),arr.sum(axis=0),arr.cumsum

In [103]:
np.mean(rand),np.sum(rand)

(0.0154892590154308, 0.2478281442468928)

In [105]:
rand.mean(axis=1) #axis = 1 means row wise mean calculation.

array([-0.00534197, -0.19189388, -0.46148642,  0.72067931])

In [120]:
rand.sum(axis=0) # axis = 0 means column wise sum

array([ 0.6400986 , -1.86734658, -0.38299332,  1.85806945])

In [122]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [123]:
arr.cumsum() #cumulative sum

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [124]:
np.std(rand)

0.7429631148574768

### Sorting

In [126]:
arr = np.random.randn(6)
arr

array([ 0.81946237,  0.64048308,  0.68140756, -1.4073026 ,  0.56466512,
        0.61578184])

In [128]:
arr.sort()
arr

array([-1.4073026 ,  0.56466512,  0.61578184,  0.64048308,  0.68140756,
        0.81946237])

In [130]:
arr = np.random.randn(5, 3)
arr

array([[ 1.29066973, -0.23358115, -1.05665479],
       [-0.6749983 ,  0.0115827 ,  0.01065793],
       [-1.13051475,  0.45959865,  1.27354399],
       [ 0.8690384 , -0.39458823,  1.59827656],
       [-0.16232014,  0.2323165 , -2.25667646]])

In [131]:
arr.sort(1) # axis=1; row wise sorting
arr

array([[-1.05665479, -0.23358115,  1.29066973],
       [-0.6749983 ,  0.01065793,  0.0115827 ],
       [-1.13051475,  0.45959865,  1.27354399],
       [-0.39458823,  0.8690384 ,  1.59827656],
       [-2.25667646, -0.16232014,  0.2323165 ]])

### Unique and Other Set Logic

### np.unique

np.unique returns unique sorted value.

In [132]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [133]:
np.unique(names),np.unique(ints)

(array(['Bob', 'Joe', 'Will'], dtype='<U4'), array([1, 2, 3, 4]))

###  np.in1d

In [135]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [136]:
#returns an array of true and flase. It is true if value of values array is found in the [2,3,6]
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

### File Input and Output with Arrays

In [137]:
ara = np.arange(10)
ara

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.save('arafile',ara)

In [140]:
np.load('arafile.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
np.savez('array_archive.npz', a=arr, b=arr)

In [144]:
ara = np.load('array_archive.npz')
ara['a'],ara['b']

(array([[-1.05665479, -0.23358115,  1.29066973],
        [-0.6749983 ,  0.01065793,  0.0115827 ],
        [-1.13051475,  0.45959865,  1.27354399],
        [-0.39458823,  0.8690384 ,  1.59827656],
        [-2.25667646, -0.16232014,  0.2323165 ]]),
 array([[-1.05665479, -0.23358115,  1.29066973],
        [-0.6749983 ,  0.01065793,  0.0115827 ],
        [-1.13051475,  0.45959865,  1.27354399],
        [-0.39458823,  0.8690384 ,  1.59827656],
        [-2.25667646, -0.16232014,  0.2323165 ]]))

### Linear Algebra

In [146]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [149]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [150]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

#### from numpy.linalg import inv, qr

matrix decomposition,inverse,determinant etc are found in that library

In [186]:
from numpy.linalg import inv, qr,det,eig,pinv,svd,solve

In [164]:
ara = np.arange(1,10).reshape((3,3))

In [169]:
inv(ara)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [166]:
det(ara) #determinant

6.66133814775094e-16

In [175]:
np.diag(ara) #return diagonal element

array([1, 5, 9])

In [176]:
np.trace(ara) #compute the sum of the diagonal

15

In [180]:
eig(ara) #Compute the eigenvalues and eigenvectors of a square matrix

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [182]:
pinv(ara) #Compute the Moore-Penrose pseudo-inverse of a matrix

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02, -2.60208521e-16,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [184]:
svd(ara) #Compute the singular value decomposition (SVD)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 1.47280825e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [ 0.40824829, -0.81649658,  0.40824829]]))

Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:

In [190]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])

In [192]:
x = np.linalg.solve(a, b)
x

array([2., 3.])